- uses: actions/setup-node@v4
  with:
    node-version: 22
- run: corepack enable
- run: yarn install --immutable
# v5 build
- uses: actions/cache@v4
  id: site-cache
  name: Load webpack cache
  with:
    path: "packages/documentation-site/.cache"
    key: ${{ runner.os }}-${{ hashFiles('yarn.lock') }}
- run: yarn build
  name: Build docs
