- uses: actions/setup-node@v1
  with:
    node-version: '14'
- uses: actions/cache@v2
  id: yarn-cache
  name: Load v3 and v4 npm deps from cache
  with:
    path: '**/node_modules'
    key: ${{ runner.os }}-yarn-14-${{ hashFiles('yarn.lock') }}
- run: yarn install --frozen-lockfile
  if: steps.yarn-cache.outputs.cache-hit != 'true'
# v3 build
- uses: actions/cache@v2
  id: v3-artifact-cache
  name: Load v3 artifact from cache
  with:
    path: 'build/patternfly-org/v3'
    key: ${{ runner.os }}-build-${{ hashFiles('packages/v3/*', 'packages/v3/**') }}
- uses: ruby/setup-ruby@v1
  with:
    ruby-version: 2.6
  if: steps.v3-artifact-cache.outputs.cache-hit != 'true'
- run: cd packages/v3 && bundle install --jobs 4 --retry 3
  name: Install v3 ruby deps
  if: steps.v3-artifact-cache.outputs.cache-hit != 'true'
- run: yarn build:v3
  name: Build v3 docs
  if: steps.v3-artifact-cache.outputs.cache-hit != 'true'

