- uses: actions/setup-node@v1
  with:
    node-version: "20"
- uses: actions/cache@v2
  id: yarn-cache
  name: Load npm deps from cache
  with:
    path: "**/node_modules"
    key: ${{ runner.os }}-yarn-14-${{ hashFiles('yarn.lock') }}
- run: yarn install --frozen-lockfile
  if: steps.yarn-cache.outputs.cache-hit != 'true'
# v5 build
- uses: actions/cache@v2
  id: site-cache
  name: Load webpack cache
  with:
    path: "packages/documentation-site/.cache"
    key: ${{ runner.os }}-${{ hashFiles('yarn.lock') }}
- run: yarn build
  name: Build docs
