name: Weekly Slack Monitor Rotation

on:
  schedule:
    # Runs at 9:00 AM every Monday (UTC)
    - cron: '0 9 * * 1'
  # Also allow manual trigger for testing
  workflow_dispatch:

jobs:
  rotate-monitor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
      
      - name: Run rotation script
        env:
          SLACK_TOKEN: ${{ secrets.SLACK_MONITOR_APP_SLACK_TOKEN }}
          CHANNEL_ID: ${{ secrets.TEAM_UXD_PATTERNFLY_CHANNEL_ID }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          EXCLUDED_USERS: ${{ secrets.SLACK_MONITOR_EXCLUDED_USERS }}
        run: python scripts/slack_monitor_rotation.py
