nodeLinker: node-modules
packageExtensions:
  "@patternfly/patternfly-doc-core@*":
    peerDependenciesMeta:
      astro:
        optional: true
      "@patternfly/react-icons":
        optional: true
