#/bin/sh

# This script is called from .travis.yml, upon a successful build, and commits 
# generated files to a seperate branch. Note that this script depends on 
# AUTH_TOKEN being set via Travis CI configuration.

set -o errexit -o nounset

if [ "$TRAVIS_BRANCH" != "master" ]
then
  echo "This commit was made against the $TRAVIS_BRANCH and not the master! Do not deploy!"
  exit 0
fi

# User info
git config --global user.name "Admin"
git config --global user.email "patternfly@redhat.com"

# Add upstream authentication token
git remote add upstream https://$AUTH_TOKEN@github.com/patternfly/patternfly-org.git
git fetch

# Commit generated files
git add source/assets/css source/components --force
git commit -m "Added files generated by Travis build"

# Push to remote branch
git push upstream $TRAVIS_BRANCH:releases --force

exit $?
