
        import React from 'react';
        import docs from '/Users/jschuler/Documents/GitHub/org-patternfly-base/packages/patternfly-4/_repos/react-core/src/components/Nav/Nav.docs.js';
        import ComponentDocs from '/Users/jschuler/Documents/GitHub/org-patternfly-base/packages/patternfly-4/src/components/componentDocs';

        const rawExamples = [{name: 'NavDefaultList', path: '../_repos/react-core/src/components/Nav/examples/NavDefaultList.js', file: require('!!raw-loader!../_repos/react-core/src/components/Nav/examples/NavDefaultList.js')},{name: 'NavExpandableTitlesList', path: '../_repos/react-core/src/components/Nav/examples/NavExpandableTitlesList.js', file: require('!!raw-loader!../_repos/react-core/src/components/Nav/examples/NavExpandableTitlesList.js')},{name: 'NavExpandableList', path: '../_repos/react-core/src/components/Nav/examples/NavExpandableList.js', file: require('!!raw-loader!../_repos/react-core/src/components/Nav/examples/NavExpandableList.js')},{name: 'NavGroupedList', path: '../_repos/react-core/src/components/Nav/examples/NavGroupedList.js', file: require('!!raw-loader!../_repos/react-core/src/components/Nav/examples/NavGroupedList.js')},{name: 'NavHorizontalList', path: '../_repos/react-core/src/components/Nav/examples/NavHorizontalList.js', file: require('!!raw-loader!../_repos/react-core/src/components/Nav/examples/NavHorizontalList.js')},{name: 'NavMixedList', path: '../_repos/react-core/src/components/Nav/examples/NavMixedList.js', file: require('!!raw-loader!../_repos/react-core/src/components/Nav/examples/NavMixedList.js')},{name: 'NavSimpleList', path: '../_repos/react-core/src/components/Nav/examples/NavSimpleList.js', file: require('!!raw-loader!../_repos/react-core/src/components/Nav/examples/NavSimpleList.js')},{name: 'NavTertiaryList', path: '../_repos/react-core/src/components/Nav/examples/NavTertiaryList.js', file: require('!!raw-loader!../_repos/react-core/src/components/Nav/examples/NavTertiaryList.js')}];
        const images = [{name: 'img_avatar.svg', file: require('../_repos/react-core/src/demos/PageLayout/examples/img_avatar.svg')},{name: 'l_pf-reverse-164x11.png', file: require('../_repos/react-core/src/demos/PageLayout/examples/l_pf-reverse-164x11.png')},{name: 'img_avatar.svg', file: require('../_repos/react-core/src/components/Avatar/examples/img_avatar.svg')},{name: 'pf_logo.svg', file: require('../_repos/react-core/src/components/Brand/examples/pf_logo.svg')},{name: 'pf_logo.svg', file: require('../_repos/react-core/src/components/AboutModal/examples/pf_logo.svg')},{name: 'pf_mini_logo_white.svg', file: require('../_repos/react-core/src/components/AboutModal/examples/pf_mini_logo_white.svg')},{name: 'pf_logo_color.svg', file: require('../_repos/react-core/src/components/LoginPage/examples/pf_logo_color.svg')},{name: 'pfbg_992.jpg', file: require('../_repos/react-core/src/components/AboutModal/examples/pfbg_992.jpg')}];

        export const nav_docs = docs;
        export const nav_package = 'react-core';

        export default () => <ComponentDocs rawExamples={rawExamples} images={images} {...docs} />;
        