
        import React from 'react';
        import docs from '/Users/jschuler/Documents/GitHub/org-patternfly-base/packages/patternfly-4/_repos/react-core/src/components/Progress/Progress.docs.js';
        import ComponentDocs from '/Users/jschuler/Documents/GitHub/org-patternfly-base/packages/patternfly-4/src/components/componentDocs';

        const rawExamples = [{name: 'LabeledProgress', path: '../_repos/react-core/src/components/Progress/examples/LabeledProgress.js', file: require('!!raw-loader!../_repos/react-core/src/components/Progress/examples/LabeledProgress.js')},{name: 'ProgressFailure', path: '../_repos/react-core/src/components/Progress/examples/ProgressFailure.js', file: require('!!raw-loader!../_repos/react-core/src/components/Progress/examples/ProgressFailure.js')},{name: 'LargeProgress', path: '../_repos/react-core/src/components/Progress/examples/LargeProgress.js', file: require('!!raw-loader!../_repos/react-core/src/components/Progress/examples/LargeProgress.js')},{name: 'ProgressFailureWithoutMeasure', path: '../_repos/react-core/src/components/Progress/examples/ProgressFailureWithoutMeasure.js', file: require('!!raw-loader!../_repos/react-core/src/components/Progress/examples/ProgressFailureWithoutMeasure.js')},{name: 'ProgressInside', path: '../_repos/react-core/src/components/Progress/examples/ProgressInside.js', file: require('!!raw-loader!../_repos/react-core/src/components/Progress/examples/ProgressInside.js')},{name: 'ProgressInsideSuccess', path: '../_repos/react-core/src/components/Progress/examples/ProgressInsideSuccess.js', file: require('!!raw-loader!../_repos/react-core/src/components/Progress/examples/ProgressInsideSuccess.js')},{name: 'ProgressOutside', path: '../_repos/react-core/src/components/Progress/examples/ProgressOutside.js', file: require('!!raw-loader!../_repos/react-core/src/components/Progress/examples/ProgressOutside.js')},{name: 'ProgressOutsideFailure', path: '../_repos/react-core/src/components/Progress/examples/ProgressOutsideFailure.js', file: require('!!raw-loader!../_repos/react-core/src/components/Progress/examples/ProgressOutsideFailure.js')},{name: 'ProgressSuccess', path: '../_repos/react-core/src/components/Progress/examples/ProgressSuccess.js', file: require('!!raw-loader!../_repos/react-core/src/components/Progress/examples/ProgressSuccess.js')},{name: 'ProgressWithDynamicDescription', path: '../_repos/react-core/src/components/Progress/examples/ProgressWithDynamicDescription.js', file: require('!!raw-loader!../_repos/react-core/src/components/Progress/examples/ProgressWithDynamicDescription.js')},{name: 'ProgressWithoutMeasure', path: '../_repos/react-core/src/components/Progress/examples/ProgressWithoutMeasure.js', file: require('!!raw-loader!../_repos/react-core/src/components/Progress/examples/ProgressWithoutMeasure.js')},{name: 'SimpleProgress', path: '../_repos/react-core/src/components/Progress/examples/SimpleProgress.js', file: require('!!raw-loader!../_repos/react-core/src/components/Progress/examples/SimpleProgress.js')},{name: 'SmallProgress', path: '../_repos/react-core/src/components/Progress/examples/SmallProgress.js', file: require('!!raw-loader!../_repos/react-core/src/components/Progress/examples/SmallProgress.js')}];
        const images = [{name: 'img_avatar.svg', file: require('../_repos/react-core/src/demos/PageLayout/examples/img_avatar.svg')},{name: 'l_pf-reverse-164x11.png', file: require('../_repos/react-core/src/demos/PageLayout/examples/l_pf-reverse-164x11.png')},{name: 'img_avatar.svg', file: require('../_repos/react-core/src/components/Avatar/examples/img_avatar.svg')},{name: 'pf_logo.svg', file: require('../_repos/react-core/src/components/Brand/examples/pf_logo.svg')},{name: 'pf_logo.svg', file: require('../_repos/react-core/src/components/AboutModal/examples/pf_logo.svg')},{name: 'pf_mini_logo_white.svg', file: require('../_repos/react-core/src/components/AboutModal/examples/pf_mini_logo_white.svg')},{name: 'pf_logo_color.svg', file: require('../_repos/react-core/src/components/LoginPage/examples/pf_logo_color.svg')},{name: 'pfbg_992.jpg', file: require('../_repos/react-core/src/components/AboutModal/examples/pfbg_992.jpg')}];

        export const progress_docs = docs;
        export const progress_package = 'react-core';

        export default () => <ComponentDocs rawExamples={rawExamples} images={images} {...docs} />;
        