#/bin/sh

set -o errexit -o nounset

# User info
git config user.name "patternfly-build"
git config user.email "patternfly-build@redhat.com"
git config --global push.default simple

# OpenShift expects "php" as application directory's document root
mv source/_site php

# Commit generated files
git add php --force
git commit -m "Added files generated by Travis build"
