#/bin/sh

set -o errexit -o nounset

# User info
git config user.name "Admin"
git config user.email "patternfly-build@redhat.com"
git config --global push.default simple

# Commit generated files
git add source/assets/css source/components --force
git commit -m "Added files generated by Travis build"
