#!/bin/sh

default()
{
  SCRIPT=`basename $0`
  SCRIPT_DIR=`dirname $0`
  SCRIPT_DIR=`cd $SCRIPT_DIR; pwd`

  . $SCRIPT_DIR/release/env.sh
  . $SCRIPT_DIR/release/common.sh

  PTNFLY_DIR=`cd $SCRIPT_DIR/..; pwd`
}

# Publish site for OpenShift and GitHub pages
#
publish_site()
{
  echo "*** Creating php directory"
  cd $PTNFLY_DIR/source/_site

  # Note: OpenShift expects "php" as application directory's document root
  mkdir -p ../../php
  find . | cpio -dumpv ../../php

  # Commit generated files
  cd $PTNFLY_DIR
  git add php --force
  git commit -m "Added files generated by Travis build"
  check $? "git commit failure"
}

usage()
{
cat <<- EEOOFF

    This script will publish generated files to GitHub.

    Note: Intended for use with Travis only.

    sh [-x] $SCRIPT [-h]

    Example: sh $SCRIPT

    OPTIONS:
    h       Display this message (default)

EEOOFF
}

# main()
{
  default

  while getopts h c; do
    case $c in
      h) usage; exit 0;;
      \?) usage; exit 1;;
    esac
  done

  # Avoid creating a dist equivalent for all branches in the main repo
  if [ "$TRAVIS_REPO_SLUG" = "$PTNFLY_REPO_SLUG" -a "$TRAVIS_BRANCH" != "master" ]; then
    echo "This commit was made against $TRAVIS_BRANCH and not the master or tag! Do not deploy!"
    exit 0
  fi

  git_setup
  publish_site # Publish site for OpenShift and GitHub pages
}
