import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Fragment, useState } from 'react';
import { Button, Content, Card, CardHeader, CardBody, CardFooter, CardTitle, ContentVariants, DescriptionList, DescriptionListDescription, DescriptionListGroup, DescriptionListTerm, Divider, Grid, GridItem, PageSection, Title } from '@patternfly/react-core';
import ArrowRightIcon from '@patternfly/react-icons/dist/esm/icons/arrow-right-icon';
import TimesIcon from '@patternfly/react-icons/dist/esm/icons/times-icon';
import MultiContentCard from '@patternfly/react-component-groups/dist/dynamic/MultiContentCard';
import AnimationsOverviewClusterInventory from './AnimationsOverviewClusterInventory';
import AnimationsOverviewNetworkActivity from './AnimationsOverviewNetworkActivity';
import AnimationsOverviewStorage from './AnimationsOverviewStorage';
import AnimationsOverviewMemoryUtilization from './AnimationsOverviewMemoryUtilization';
export const AnimationsOverview = ({ recentActivityCard, openshiftLogo }) => {
    const [displayMultiContentCard, setDisplayMultiContentCard] = useState(true);
    const handleCloseMultiContentCard = () => {
        setDisplayMultiContentCard(false);
    };
    const cards = [
        // Card 1: Performance
        _jsxs(Card, { isFullHeight: true, isPlain: true, children: [_jsx(CardHeader, { children: _jsx(Content, { component: ContentVariants.h3, children: "Animations" }) }), _jsx(CardBody, { children: _jsx(Content, { component: ContentVariants.p, className: "pf-v6-u-mb-sm", children: "Our new animations bring more clarity and expression to your screen. They let you interact with your data in a new way, with engaging data visualizations that are even easier to understand and use." }) }), _jsx(CardFooter, { children: _jsx(Button, { variant: "link", icon: _jsx(ArrowRightIcon, {}), iconPosition: "end", isInline: true, children: _jsx("a", { href: "https://www.patternfly.org/foundations-and-styles/motion", children: "They're everywhere" }) }) })] }, "card-1"),
        // Card 2: Stability
        _jsxs(Card, { isFullHeight: true, isPlain: true, children: [_jsx(CardHeader, { children: _jsx(Content, { component: ContentVariants.h3, children: "Network security" }) }), _jsx(CardBody, { children: _jsx(Content, { component: ContentVariants.p, className: "pf-v6-u-mb-sm", children: "Network security is a critical part of any organization's security posture." }) }), _jsx(CardFooter, { children: _jsx(Button, { variant: "link", icon: _jsx(ArrowRightIcon, {}), iconPosition: "end", isInline: true, children: "Security updates" }) })] }, "card-2"),
        // Card 3: Availability
        _jsxs(Card, { isFullHeight: true, isPlain: true, children: [_jsx(CardHeader, { children: _jsx(Content, { component: ContentVariants.h3, children: "Cluster alerting" }) }), _jsx(CardBody, { children: _jsx(Content, { component: ContentVariants.p, className: "pf-v6-u-mb-sm", children: "Cluster alerting is a critical part of any organization's security posture." }) }), _jsx(CardFooter, { children: _jsx(Button, { variant: "link", icon: _jsx(ArrowRightIcon, {}), iconPosition: "end", isInline: true, children: "View logs" }) })] }, "card-3"),
        // Card 4: Image
        _jsx(Card, { isFullHeight: true, isPlain: true, children: _jsx(CardBody, { children: _jsx("img", { src: openshiftLogo, alt: "OpenShift Logo", style: { width: '200px', height: '200px' } }) }) }, "card-4")
    ];
    return (_jsxs(Fragment, { children: [displayMultiContentCard && (_jsx(PageSection, { id: "overview", children: _jsx(MultiContentCard, { isExpandable: true, withDividers: true, cards: cards, toggleText: "What's new in OpenShift?", actions: _jsx(Button, { icon: _jsx(TimesIcon, {}), variant: "plain", onClick: handleCloseMultiContentCard }) }) })), _jsx(PageSection, { "aria-label": "Detail status events", children: _jsxs(Grid, { hasGutter: true, children: [_jsx(GridItem, { span: 12, sm: 12, md: 6, lg: 4, xl: 3, rowSpan: 4, children: _jsxs(Card, { isFullHeight: true, children: [_jsx(CardTitle, { children: _jsx(Title, { headingLevel: "h4", size: "xl", children: "Cluster Details" }) }), _jsx(CardBody, { children: _jsxs(DescriptionList, { children: [_jsxs(DescriptionListGroup, { children: [_jsx(DescriptionListTerm, { children: "Cluster API Address" }), _jsx(DescriptionListDescription, { children: _jsx("a", { href: "#", children: "https://api1.devcluster.openshift.com" }) })] }), _jsxs(DescriptionListGroup, { children: [_jsx(DescriptionListTerm, { children: "Cluster ID" }), _jsx(DescriptionListDescription, { children: "63b97ac1-b850-41d9-8820-239becde9e86" })] }), _jsxs(DescriptionListGroup, { children: [_jsx(DescriptionListTerm, { children: "Provide" }), _jsx(DescriptionListDescription, { children: "AWS" })] }), _jsxs(DescriptionListGroup, { children: [_jsx(DescriptionListTerm, { children: "OpenShift Version" }), _jsx(DescriptionListDescription, { children: "4.5.0.ci-2020-06-16-015028" })] }), _jsxs(DescriptionListGroup, { children: [_jsx(DescriptionListTerm, { children: "Update Channel" }), _jsx(DescriptionListDescription, { children: "stable-4.5" })] })] }) }), _jsx(Divider, {}), _jsx(CardFooter, { children: _jsx("a", { href: "#", children: "View Settings" }) })] }) }), _jsx(GridItem, { span: 12, sm: 12, md: 6, lg: 4, xl: 3, rowSpan: 2, children: _jsx(AnimationsOverviewClusterInventory, {}) }), _jsx(GridItem, { span: 12, sm: 12, md: 6, lg: 4, xl: 3, rowSpan: 2, children: _jsx(AnimationsOverviewStorage, {}) }), _jsx(GridItem, { span: 12, sm: 12, md: 12, lg: 8, xl: 3, rowSpan: 2, children: _jsx(AnimationsOverviewMemoryUtilization, {}) }), _jsx(GridItem, { span: 12, sm: 12, md: 12, lg: 12, xl: 3, rowSpan: 2, children: _jsx(AnimationsOverviewNetworkActivity, {}) }), recentActivityCard && (_jsx(GridItem, { span: 12, sm: 12, md: 12, lg: 8, xl: 6, rowSpan: 2, children: recentActivityCard }))] }) })] }));
};
export default AnimationsOverview;
//# sourceMappingURL=AnimationsOverview.js.map