import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Fragment, useState } from 'react';
import { Card, CardBody, CardFooter, CardHeader, CardTitle, DescriptionList, DescriptionListDescription, DescriptionListGroup, DescriptionListTerm, Divider, Flex, FlexItem, Icon, MenuToggle, Select, SelectList, SelectOption, Spinner, Timestamp, Title } from '@patternfly/react-core';
import CheckCircleIcon from '@patternfly/react-icons/dist/esm/icons/check-circle-icon';
import ExclamationCircleIcon from '@patternfly/react-icons/dist/esm/icons/exclamation-circle-icon';
const AnimationsOverviewEventsCard = () => {
    const [isOpen, setIsOpen] = useState(false);
    const selectItems = (_jsxs(SelectList, { children: [_jsx(SelectOption, { value: "Success", children: "Success" }, "option1"), _jsx(SelectOption, { value: "Error", children: "Error" }, "option2"), _jsx(SelectOption, { value: "Warning", children: "Warning" }, "option3")] }));
    const toggle = (toggleRef) => (_jsx(MenuToggle, { ref: toggleRef, onClick: () => setIsOpen(!isOpen), isExpanded: isOpen, variant: "plainText", children: "Status" }));
    const headerActions = (_jsx(Select, { onSelect: () => setIsOpen(!isOpen), onOpenChange: setIsOpen, isOpen: isOpen, toggle: toggle, children: selectItems }));
    return (_jsx(Fragment, { children: _jsxs(Card, { id: "card-events-view-example", children: [_jsx(CardHeader, { actions: { actions: headerActions, hasNoOffset: true }, children: _jsx(CardTitle, { children: _jsx(Title, { headingLevel: "h4", size: "xl", children: "Events" }) }) }), _jsx(CardBody, { children: _jsxs(DescriptionList, { children: [_jsxs(DescriptionListGroup, { children: [_jsx(DescriptionListTerm, { children: _jsxs(Flex, { flexWrap: { default: 'nowrap' }, children: [_jsx(FlexItem, { children: _jsx(Icon, { status: "danger", children: _jsx(ExclamationCircleIcon, {}) }) }), _jsx(FlexItem, { children: _jsx("span", { children: "Readiness probe failed" }) })] }) }), _jsx(DescriptionListDescription, { children: "Readiness probe failed: Get https://10.131.0.7:5000/healthz: dial tcp 10.131.0.7:5000: connect: connection refused" }), _jsx(DescriptionListDescription, { children: _jsx(Timestamp, { date: new Date('2023-06-17T11:02'), dateFormat: "medium", timeFormat: "short" }) })] }), _jsxs(DescriptionListGroup, { children: [_jsx(DescriptionListTerm, { children: _jsxs(Flex, { flexWrap: { default: 'nowrap' }, children: [_jsx(FlexItem, { children: _jsx(Icon, { status: "success", children: _jsx(CheckCircleIcon, {}) }) }), _jsx(FlexItem, { children: _jsx("span", { children: "Successful assignment" }) })] }) }), _jsx(DescriptionListDescription, { children: "Successfully assigned default/example to ip-10-0-130-149.ec2.internal" }), _jsx(DescriptionListDescription, { children: _jsx(Timestamp, { date: new Date('2023-06-17T11:13'), dateFormat: "medium", timeFormat: "short" }) })] }), _jsxs(DescriptionListGroup, { children: [_jsx(DescriptionListTerm, { children: _jsxs(Flex, { flexWrap: { default: 'nowrap' }, children: [_jsx(FlexItem, { children: _jsx(Spinner, { size: "md", "aria-label": "loading spinner" }) }), _jsx(FlexItem, { children: _jsx("span", { children: "Pulling image" }) })] }) }), _jsx(DescriptionListDescription, { children: "Pulling image \"openshift/hello-openshift\"" }), _jsx(DescriptionListDescription, { children: _jsx(Timestamp, { date: new Date('2023-06-17T10:59'), dateFormat: "medium", timeFormat: "short" }) })] }), _jsxs(DescriptionListGroup, { children: [_jsx(DescriptionListTerm, { children: _jsxs(Flex, { flexWrap: { default: 'nowrap' }, children: [_jsx(FlexItem, { children: _jsx(Icon, { status: "success", children: _jsx(CheckCircleIcon, {}) }) }), _jsx(FlexItem, { children: _jsx("span", { children: "Created container" }) })] }) }), _jsx(DescriptionListDescription, { children: "Created container hello-openshift" }), _jsx(DescriptionListDescription, { children: _jsx(Timestamp, { date: new Date('2023-06-17T10:45'), dateFormat: "medium", timeFormat: "short" }) })] })] }) }), _jsx(Divider, {}), _jsx(CardFooter, { children: _jsx("a", { href: "#", children: "View all events" }) })] }) }));
};
export default AnimationsOverviewEventsCard;
//# sourceMappingURL=AnimationsOverviewEventsCard.js.map