name: build-deploy
on: [push]
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    env:
      SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}
      SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
      GH_PR_TOKEN: ${{ secrets.GH_PR_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
      - run: yarn install --frozen-lockfile
      # v4 build
      - run: yarn build:v4
      - run: node .github/upload-preview.js build/patternfly-org v4
      # v3 build
      - run: cd packages/v3 && bundle install --jobs 4 --retry 3
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6'
      - run: yarn build:v3
      - run: node .github/upload-preview.js build/patternfly-org v3
      # deploy
      - run: ls build/patternfly-org/
