name: Add new issues to project board

on:
  issues:
    types:
      - opened

jobs:
  add-to-extensions:
    name: Add issue to extensions board
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v0.3.0
        with:
          project-url: https://github.com/orgs/patternfly/projects/12
          github-token: ${{ secrets.GH_PROJECTS }}
