name: pr-preview
on: pull_request_target
jobs:
  build-upload:
    runs-on: ubuntu-latest
    env:
      SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}
      SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
      GH_PR_TOKEN: ${{ secrets.GH_PR_TOKEN }}
      GH_PR_NUM:   ${{ github.event.number }}
    steps:
      - uses: actions/checkout@v2
# Pending https://github.com/actions/runner/issues/646 we can make this a composite action.
# COMMON BUILD -- if editing also edit release.yml
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - uses: actions/cache@v2
        id: yarn-cache
        name: Load v3 and v4 npm deps from cache
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
      - run: yarn install --frozen-lockfile
        if: steps.yarn-cache.outputs.cache-hit != 'true'
      # v4 build
      - uses: actions/cache@v2
        id: v4-cache
        name: Load webpack cache
        with:
          path: 'packages/v4/.cache'
          key: ${{ runner.os }}-v4-${{ hashFiles('yarn.lock') }}
      - run: yarn build:v4
        name: Build docs
      # v3 build
      - uses: actions/cache@v2
        id: v3-artifact-cache
        name: Load v3 artifact from cache
        with:
          path: 'build/patternfly-org/v3'
          key: ${{ runner.os }}-build-${{ hashFiles('packages/v3/*', 'packages/v3/**') }}
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6'
        if: steps.v3-artifact-cache.outputs.cache-hit != 'true'
      - run: cd packages/v3 && bundle install --jobs 4 --retry 3
        name: Install v3 ruby deps
        if: steps.v3-artifact-cache.outputs.cache-hit != 'true'
      - run: yarn build:v3
        name: Build v3 docs
        if: steps.v3-artifact-cache.outputs.cache-hit != 'true'
# END COMMON BUILD
      # move v3 docs out to be uploaded separately
      - run: mkdir tmp
      - run: mv build/patternfly-org/v3 tmp
      - run: node .github/upload-preview.js build/patternfly-org v4
        name: Upload docs
      # only take the time to upload v3 if there's a change
      - run: node .github/upload-preview.js tmp v3
        name: Upload v3 docs
        if: steps.v3-artifact-cache.outputs.cache-hit != 'true'

