name: release
on:
  push:
    branches:
      - main
jobs:
  build-deploy:
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN_REDALLEN }} # needs to be an admin token to get around branch protection
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - run: printenv
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN_REDALLEN }} # needs to be an admin token to get around branch protection
# Pending https://github.com/actions/runner/issues/646 we can make this a composite action.
# COMMON BUILD -- if editing also edit release.yml
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
      - uses: actions/cache@v2
        id: yarn-cache
        name: Load v3 and v4 npm deps from cache
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
      - run: yarn install --frozen-lockfile
        if: steps.yarn-cache.outputs.cache-hit != 'true'
# THIS IS THE ONLY STEP THAT IS DIFFERENT
      - run: .github/release.sh
      # v4 build
      - uses: actions/cache@v2
        id: v4-cache
        name: Load webpack cache
        with:
          path: 'packages/v4/.cache'
          key: ${{ runner.os }}-v4-${{ hashFiles('yarn.lock') }}
      - run: yarn build:v4
        name: Build docs
      # v3 build
      - uses: actions/cache@v2
        id: v3-artifact-cache
        name: Load v3 artifact from cache
        with:
          path: 'build/patternfly-org/v3'
          key: ${{ runner.os }}-build-${{ hashFiles('packages/v3/*', 'packages/v3/**') }}
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
        if: steps.v3-artifact-cache.outputs.cache-hit != 'true'
      - run: cd packages/v3 && bundle install --jobs 4 --retry 3
        name: Install v3 ruby deps
        if: steps.v3-artifact-cache.outputs.cache-hit != 'true'
      - run: yarn build:v3
        name: Build v3 docs
        if: steps.v3-artifact-cache.outputs.cache-hit != 'true'
# END COMMON BUILD
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY}}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - run: node scripts/writeV3Redirects.js
      - run: node scripts/writeVersionPrefix.js
      - run: du -sh build/patternfly-org/*
        name: Check size of docs
      - run: .github/upload-staging.sh
        name: Upload docs to staging
