name: release
on:
  push:
    branches:
      - main
jobs:
  build-deploy:
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN_REDALLEN }} # needs to be an admin token to get around branch protection
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - run: printenv
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN_REDALLEN }} # needs to be an admin token to get around branch protection
      - id: build
        uses: ./.github/actions/build@v1
      - run: .github/release.sh
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY}}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - run: node scripts/writeV3Redirects.js
      - run: node scripts/writeVersionPrefix.js
      - run: du -sh build/patternfly-org/*
        name: Check size of docs
      - run: .github/upload-staging.sh
        name: Upload docs to staging
