name: pr-preview
on:
  pull_request_target:
  issue_comment:
    types: [created]
jobs:
  check-permissions:
    uses: patternfly/.github/.github/workflows/check-team-membership.yml@main
    secrets: inherit

  build-upload:
    runs-on: ubuntu-latest
    needs: check-permissions
    if: needs.check-permissions.outputs.allowed == 'true'
    env:
      SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}
      SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
      GH_PR_TOKEN: ${{ secrets.GH_PR_TOKEN }}
      GH_PR_NUM: ${{ needs.check-permissions.outputs.pr-number }}
    steps:
      - uses: actions/checkout@v4
      # Yes, we really want to checkout the PR
      - run: |
          git fetch origin pull/$GH_PR_NUM/head:tmp
          git checkout tmp
      # Injected by generate-workflows.js
      %build%
      - run: node .github/upload-preview.js build/patternfly-org/site site
        name: Upload docs
  build-upload-astro:
    runs-on: ubuntu-latest
    needs: check-permissions
    if: needs.check-permissions.outputs.allowed == 'true'
    env:
      SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}
      SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
      GH_PR_TOKEN: ${{ secrets.GH_PR_TOKEN }}
      GH_PR_NUM: ${{ needs.check-permissions.outputs.pr-number }}
    steps:
      - uses: actions/checkout@v4
      - run: |
          git fetch origin pull/$GH_PR_NUM/head:tmp
          git checkout tmp
      # Injected by generate-workflows.js
      %build-astro%
